# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            QDC SLG
tagline:          'QDC SLG'
description:      'Time to write somthing down.'
url:              http://qdcslg.github.io/

author:
  name:           'QDC SLG'
  url:            http://qdcslg.github.io/

paginate:         2
google_analytics: ''
bing_seo:		  ''
emailme:          mailto:qdc@slg.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/qdcslg/qdcslg.github.io/

tags:

github_username:  qdcslg
facebook_username: none
linkedin_username: none


